export const SET_CURRENT_STOPS_GEOJSON = 'SET_CURRENT_STOPS_GEOJSON';
export const SET_CURRENT_MOT = 'SET_CURRENT_MOT';
export const SET_CLICK_LOCATION = 'SET_CLICK_LOCATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SET_IS_FIELD_FOCUSED = 'SET_IS_FIELD_FOCUSED';
