export const SET_CENTER = 'SET_CENTER';
export const SET_CURRENT_STOPS = 'SET_CURRENT_STOPS';
export const SET_CURRENT_STOPS_GEOJSON = 'SET_CURRENT_STOPS_GEOJSON';
export const SET_CURRENT_MOT = 'SET_CURRENT_MOT';
export const SET_CLICK_LOCATION = 'SET_CLICK_LOCATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SET_IS_FIELD_FOCUSED = 'SET_IS_FIELD_FOCUSED';
export const SET_SHOW_LOADING_BAR = 'SET_SHOW_LOADING_BAR';
